### ISSUE TITLE
Response missed in Track2 SDK

### ISSUE THREAD

**Issue by dw511214992** [Azure/autorest.typescript#1037]
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2430-L2468

Track1:

Method:
```
checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<Models.ResourceGroupsCheckExistenceResponse>;
```
Response Model:
```
export type ResourceGroupsCheckExistenceResponse = {
    /**
     * The parsed response body.
     */
    body: boolean;
    /**
     * The underlying HTTP response.
     */
    _response: msRest.HttpResponse & {
        /**
         * The response body as text (string format)
         */
        bodyAsText: string;
        /**
         * The response body as parsed JSON or XML
         */
        parsedBody: boolean;
    };
};
```
Track2:
```
checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<void>;
```
Comparing the responses of methods in Track1 and Track2, we can find there is no response in Track2 and we cannot get any information from the rest api.

**Comment by deyaaeldeen** [comment]
I am looking at the swagger here: https://github.com/Azure/azure-rest-api-specs/blob/61e7148e9592c5efc95e5c16a5bb4f2dc26d6de0/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L2454. Why the responses section does not have an entry for 200?

**Comment by sarangan12** [comment]
@dw511214992 I have looked into this issue and the swagger. I agree that the V4 version of the SDK is producing a body of type boolean. But, per swagger there is no body defined. So, I will consider the V4 version only as a bug. The V6 version is working correctly per the swagger. 

Also, I have checked the operation spec in the v4 generator. So, even though the response has a body I do not see it getting deserialized and used. So, if this is a bug that should be fixed, then it should be fixed in V4. Not V6.

Could you please explain, if there is a problem if body-boolean is removed in v6?

**Comment by dw511214992** [comment]
hi @sarangan12 If the method returns `Promise<void>`, I cannot get the result of the rest api call. So how can I check wether the service existis or not in `checkExistence(resourceGroupName: string, options?: ResourceGroupsCheckExistenceOptionalParams):Promise<void>;`?

**Comment by sarangan12** [comment]
@dw511214992 Agreed. Even in v4, the operationSpec does not have anything related. So, the `body` will not be deserialized at all.

I agree that there has to be a body. My point is that such a thing must be mentioned in the swagger. In this case, it is not mentioned at all.

**Comment by dw511214992** [comment]
@sarangan12 I think the swagger definition is correct. User can check wether the resource exists by the response code: `200` represents `Found` and `404` represents `Not Found`. So I think Codegen should handle this as a special case. How do you think? thanks

**Comment by sarangan12** [comment]
The response code `204` and `404` themselves do not represent anything by themselves. They need a body defined to make that happen. 

I will try hunting down the logic in v4 if any such thing is happening. To the best of my knowledge, nothing like that happens which makes me suspect that something might be happening in autorest core. I will discuss with autorest crew and get back to you.

**Comment by dw511214992** [comment]
thanks @sarangan12

**Comment by sarangan12** [comment]
@dw511214992 I have confirmed with autorest crew that this logic has been removed V3 version of autorest. Now, the only way to do this is on the generator side. I have analyzed the required code changes to do this. It would create complexity in the code. On the other hand, the same result could be easily achieved by the swagger transform as:

```yaml
directive:
  - from: swagger-document
    where: $.paths..head.responses['204']
    transform: >
      $.schema = {};
      $.schema["$ref"] = "#/definitions/ResourceGroupsCheckExistenceResponse";
  - from: swagger-document
    where: $.definitions
    transform: >
      $.ResourceGroupsCheckExistenceResponse = {};
      $.ResourceGroupsCheckExistenceResponse.type = 'object';
      $.ResourceGroupsCheckExistenceResponse.properties = {};
      $.ResourceGroupsCheckExistenceResponse.properties.body = {};
      $.ResourceGroupsCheckExistenceResponse.properties.body.type = 'boolean';
```

Please share your thoughts on using the above swagger transform. Thanks
