### ISSUE TITLE
FATAL: Error: Unexpected value type: sealed-choice using 6.0.0-beta5

### ISSUE THREAD

**Issue by jeremymeng** [Azure/autorest.typescript#1102]
The same swagger file works fine using beta4.

```
PLUGIN FAILURE: Unexpected value type: sealed-choice, Error: Unexpected value type: sealed-choice
    at Object.getStringForValue (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/utils/valueHelpers.js:66:19)
    at getDefaultValue (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/parameterTransforms.js:124:31)
    at populateOperationParameters (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/parameterTransforms.js:178:23)
    at /home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/parameterTransforms.js:71:56
    at Array.forEach (<anonymous>)
    at Object.transformParameters (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/parameterTransforms.js:71:43)
    at Object.<anonymous> (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:87:35)
    at Generator.next (<anonymous>)
    at fulfilled (/home/azuser/.autorest/@autorest_typescript@6.0.0-beta.5/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:7:58), {}
FATAL: Error: Unexpected value type: sealed-choice
```

swagger readme yaml:

 ```yaml
 v3: true
 package-name: "@azure/container-registry"
 title: GeneratedClient
 description: Container Registry Client
 generate-metadata: false
 license-header: MICROSOFT_MIT_NO_VERSION
 output-folder: ../
 source-code-folder-path: ./src/generated
 input-file:
 https://github.com/Azure/azure-rest-api-specs/blob/765876c2abaae9952131eb6a607e924a30b822c5/specification/containerregistry/data-plane/Azure.ContainerRegistry/stable/2021-07-01/containerregistry\
 .json
 add-credentials: false
 override-client-name: GeneratedClient
 disable-async-iterators: true
 hide-clients: true
 use-extension:
   "@autorest/typescript": "6.0.0-beta.5"
 package-version: 1.0.0-beta.4
```
