### ISSUE TITLE
[v6] Declarative way to avoid name case conversion

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1211]
Currently, if we need to keep a name as described in the swagger that doesn't conform to modeler four namer config, for example if we want a property `key_ops` in the generated code, to avoid the generator making it `keyOps` we'd need to set a complex transform (see [example](https://github.com/Azure/azure-sdk-for-js/pull/18295/files#diff-770c887a4f045e358c30cc825b93714817615bf9ca234005e42858fe4ced231c))
 
```yaml
directive:
  - from: swagger-document
    where: $.definitions.JsonWebKey.properties.key_ops
    transform: >
      $["x-ms-client-name"] = "key_ops_keep_snakecase";

modelerfour:
  naming:
    override:
      key_ops_keep_snakecase: $DO_NOT_NORMALIZE$key_ops
```

I think this can be improved in 2 different ways

1) Have a new extension in the Swagger `x-ms-keep-name` which if set to true, M4 would not pass it through the namer.
2) Even if we don't implement the new extension, if we stop doing custom case conversion in `autorest.typescript`  (see this [comment for context](https://github.com/Azure/autorest.typescript/issues/430#issuecomment-948835832)) I think we could reduce the transform to the following?

```yaml
modelerfour:
  naming:
    override:
      key_ops: key_ops
```

**Comment by MarcErdmann** [comment]
It took me a lot of time to arrive at this thread.
It would be great if this was documented better in the official docs.
My config looked like this:

````yaml
modelerfour:
  lenient-model-deduplication: true
  naming: 
    override:
      _id: _id
````

And I was frustrated that it is not working. After reading this thread, I changed it to:

````yaml
modelerfour:
  lenient-model-deduplication: true
  naming: 
    override:
      _id: $DO_NOT_NORMALIZE$_id
````
And it works!

https://github.com/Azure/autorest.typescript/issues/1546
