### ISSUE TITLE
Security type AzureKey only works if RLC output is selected

### ISSUE THREAD

**Issue by hypermoose** [Azure/autorest.typescript#1789]
Unless rest-level-client is set to true the SecurityScheme AzureKey is completely ignored.   Neither the OpenAI spec nor command line parameters work.

**Comment by MaryGao** [comment]
@hypermoose Could you share your command and swagger link with us? Let me reproduce in my local first.

**Comment by hypermoose** [comment]
The swagger link for Azure Open AI is here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json

Here is an example command file.  In this form it works but if you change rest-level-client to false it will not generate any code to use apiKey.

## General settings

`npx autorest readme.md`

```yaml
v3: true
input-file: azure-open-ai.yaml 
output-folder: generated
package-name: api-client-factory
enum-types: true
typescript: true
rest-level-client: true
```
