### ISSUE TITLE
[JS] Duplicate Interface Names in The Same Module

### ISSUE THREAD

**Issue by minhanh-phan** [Azure/autorest.typescript#1998]
The DPG generation for @azure/schema-registry package using [this tsp file](https://github.com/minhanh-phan/azure-rest-api-specs/blob/64c0f42845bc61cea5762df36b9915d3ef13fcf9/specification/schemaregistry/SchemaRegistry/main.tsp) generates a conflict within the same module. See the duplication for the `CustomPage` interface in the `models.ts` module below. 
For more reference, [here](https://github.com/Azure/azure-sdk-for-js/blob/5e1bca92c54b43bb97f8ffc52a6f0aaf0d700b4e/sdk/schemaregistry/schema-registry/src/models/models.ts) is the generated file. We expect the generated file would not have this conflict. 

```ts
/** Paged collection of Version items */
export interface CustomPage {
  /** The Version items on this page */
  value: Version[];
  /** The link to the next page of items */
  nextLink?: string;
}
```

```ts
/** Paged collection of SchemaGroup items */
export interface CustomPage {
  /** The SchemaGroup items on this page */
  value: SchemaGroup[];
  /** The link to the next page of items */
  nextLink?: string;
}
```

To reproduce:

- Set the `tsp-location.yaml` with these info
```yaml
directory: specification/schemaregistry/SchemaRegistry
commit: 64c0f42845bc61cea5762df36b9915d3ef13fcf9
repo: Azure/azure-rest-api-specs
```
- Generate
