### ISSUE TITLE
Issue #10: CADL Generated Issue in the Content Safety SDK

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#2004]
I have tried generating a new JS SDK Package for Azure AI Content Safety. In the generation process, I have found the following issue. 

**Input**
`main.tsp` - [Link](https://github.com/Azure/azure-rest-api-specs/blob/9cff12e5e7e09f9f4479de7b626b856da501d665/specification/cognitiveservices/ContentSafety/main.tsp)
`models.tsp` - [Link](https://github.com/Azure/azure-rest-api-specs/blob/9cff12e5e7e09f9f4479de7b626b856da501d665/specification/cognitiveservices/ContentSafety/models.tsp)
`routes.tsp` - [Link](https://github.com/Azure/azure-rest-api-specs/blob/9cff12e5e7e09f9f4479de7b626b856da501d665/specification/cognitiveservices/ContentSafety/routes.tsp)
`tspconfig.yaml`
```
emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    generateMetadata: true
    generateTest: false
    multiClient: false
    azureSdkForJs: true
    isModularLibrary: true
    "emitter-output-dir": "{project-root}/sdk/cognitiveservices/cognitiveservices-contentsafety"
    packageDetails:
      name: "@azure-rest/ai-content-safety"
      description: "ContentSafety Service"
```

**Steps to generate**
1. `npx tsp compile .`
2. `rushx build`

**Issue**
There are 34 errors reported in the build process.  I was able to classify them into 3 groups:

1. The property `uint8ArrayToString` has been imported from `@azure/core-util`. There is no such export.
2. The following properties have been defined both in `models.ts` & `options.ts` and causes conflict:
- AddBlockItemsOptions
- AnalyzeTextOptions
- AnalyzeImageOptions
- RemoveBlockItemsOptions
3. The generated method `_analyzeImageSend`  has issue with `body` definition. A similar issue has been observed in the `_listTextBlocklistItemsDeserialize` method also.

Please take a look. @xirzec @joheredi FYI....
