### ISSUE TITLE
Use min/maxItems constraint to emit more precise array types

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.typescript#261]
Consider a query parameter like `location=44.5645659,-123.2620435`. This is a latitude-longitude pair that would be modeled like so:

```yaml
name: location
in: query
description: "User location in lat,lng format"
required: true
type: array
minItems: 2
maxItems: 2
items:
  type: number
collectionFormat: csv
```

This will get modeled as a `number[]` in the generated method signature, but it would be nice if it could be modeled instead as a `[number, number]` which will restrict the length to 2 at compile time.

In the case where the maxItems is greater than minItems, a type like `[number, number, number?]` could be generated.
