### ISSUE TITLE
Duplicate identifier appears in modular routes generation

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/autorest.typescript#2866]
tspconfig.yaml:
```
emit:
  - "@azure-tools/typespec-ts"
options:
  "@azure-tools/typespec-ts":
    "emitter-output-dir": "{project-root}"
    generateMetadata: true
    generateTest: false
    azureSdkForJs: false
    isTypeSpecTest: true
    isModularLibrary: true
    hierarchyClient: true
    packageDetails:
      name: "@msinternal/routes"
```
Regarding `tspconfig.yaml`, I have tried adding `enableOperationGroup: true` and `enableModelNamespace: true`, but still got the same error.

Error log:
```
 Exception during run: test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(38,3): error TS2300: Duplicate identifier 'queryExpansion'.
test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(39,3): error TS2300: Duplicate identifier 'queryExpansion'. 
test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(40,3): error TS2300: Duplicate identifier 'queryContinuation'.
test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(41,3): error TS2300: Duplicate identifier 'queryContinuation'.
test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(67,5): error TS1117: An object literal cannot have multiple properties with the same name.
test/modularIntegration/generated/routes/src/classic/queryParameters/index.ts(69,5): error TS1117: An object literal cannot have multiple properties with the same name.
```

![Image](https://github.com/user-attachments/assets/51b59a6c-8e9f-4bd1-bbd5-4a8073822700)
