### ISSUE TITLE
Emitter "@azure-tools/typespec-ts" crashed! | TypeError: Cannot read properties of undefined (reading 'fromCore')

### ISSUE THREAD

**Issue by thedomeffm** [Azure/autorest.typescript#2893]
Dont know what to do. I made changes to our typespec and wanted to build the npm package for it.

The error message is useless and does not help.

```
npx tsp compile --debug .

TypeSpec compiler v0.62.0

Emitter "@azure-tools/typespec-ts" crashed! This is a bug.
Please file an issue at https://github.com/Azure/autorest.typescript/issues

TypeError: Cannot read properties of undefined (reading 'fromCore')
    at transformBody (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:186:37)
    at transformToResponseTypesForRoute (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:56:43)
    at transformToResponseTypes (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/transform/transformResponses.js:31:13)
    at transformRLCModel (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/transform/transform.js:30:23)
    at buildRLCCodeModels (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/index.js:127:37)
    at Object.$onEmit [as emitFunction] (file:///C:/Code/<project>/backend/api-specification/node_modules/@azure-tools/typespec-ts/dist/src/index.js:75:11)
    at async runEmitter (file:///C:/Code/<project>/backend/api-specification/node_modules/@typespec/compiler/dist/src/core/program.js:366:13)
    at async compile (file:///C:/Code/<project>/backend/api-specification/node_modules/@typespec/compiler/dist/src/core/program.js:123:9)
    at async compileOnce (file:///C:/Code/<project>/backend/api-specification/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:36:25)
    at async compileAction (file:///C:/Code/<project>/backend/api-specification/node_modules/@typespec/compiler/dist/src/core/cli/actions/compile/compile.js:19:9)

--------------------------------------------------
Library Version                0.33.0
TypeSpec Compiler Version      0.62.0
--------------------------------------------------

```

```yaml
# tspconfig.yaml
emit:
  - "@typespec/openapi3"
  - "@azure-tools/typespec-ts"
  - "@typespec/http-server-csharp"
options:
  "@typespec/openapi3":
    file-type: json
    omit-unreachable-types: true
  "@azure-tools/typespec-ts":
    title: "<project>-api-client"
    packageDetails:
      name: "@<project>/api-client"
      version: "1.0.0"
      description: "<project> API Client"
  "@typespec/http-server-csharp":
    output-type: "all"
```
