### ISSUE TITLE
Generator emits wrong code when an operationId is `client`

### ISSUE THREAD

**Issue by runeh** [Azure/autorest.typescript#310]
I'm consuming the swagger file from https://tripletex.no/v2/swagger.json .

The swagger file contains definitions whose operationId is `client`. The emitted code does not compile because the generator creates a method called `client` on the class which clashes with the private `client` member of the class.

In my case I'm transforming the input a bit. I don't think that's relevant to the bug, but this is the transform:

```yaml
directive:
  from: swagger-document
  where: $.paths.*.*
  transform: >
      const tag = $.tags[0];
      const opId = $.operationId;
      const parts = tag.split('/').map(e => `${e[0].toUpperCase()}${e.slice(1)}`);
      $.operationId = `${parts.join('')}_${opId}`;
```
