### ISSUE TITLE
Properties of models are always generated as non-nullable types.

### ISSUE THREAD

**Issue by Hardtack** [Azure/autorest.typescript#411]
Hi, I'm trying to generate my swagger client using _autorest.typescript_.
I tried to generate model like following
``` yaml
Foo:
  properties:
    bar:
      type: integer
    baz:
      type: string
      x-nullable: true
  required:
    - bar
    - baz
```

which means an object named `Foo` with two required properties `bar` and `baz` such that `baz` is nullable property.

Since there is a [reference](https://github.com/Azure/autorest.common/blob/7d8821d7d6c555adaffc685954e34ea1fe1c83b1/src/Model/IVariable.cs#L66) about the custom field `x-nullable`, I expected generated model to be like following.

``` typescript
export interface Foo {
  bar: number;
  baz: string | null;
}
```

However, It generated the model like following.

``` typescript
export interface Foo {
  bar: number;
  baz: string;
}
```

I can't figure out that whether it is a bug or not, since I don't know the expected usage of `x-nullable`.

Am I misunderstanding the usage of `x-nullable`? and Is there any nice way to handle nullable properties?
