### ISSUE TITLE
Duplicate operations being created for logic app connector swaggers (Note applying transforms)

### ISSUE THREAD

**Issue by anganti** [Azure/autorest.typescript#708]
@daviwil 

Duplicate operations being created for logic app connector swaggers. This is true for both TypeScript and CSharp

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/42851022/89472487-6ec71200-d735-11ea-8ee7-2bb6be19a488.png)

See attached for swagger spec and generated code (CSharp and TS)
[dropbox-connector.zip](https://github.com/Azure/autorest.typescript/files/5031635/dropbox-connector.zip)

command ran:
autorest config.yaml

config.yaml file:

```yaml
input-file: "c:\\Connectors-SDK\\src\\AzureConnectorsSdk.Tests\\SampleFiles\\dropbox-openapi.json"
version: 3.0.6306
pass-thru: "schema-validator-swagger"
directive:
  - from: swagger-document
    where: $
    transform: >-
      $["parameters"] = {"ConnectionIdParameter": { "name": "connectionId", "in": "path", "required": true, "type": "string" }}
  - from: swagger-document
    where: $.paths.*.*.parameters[?(@.name === "connectionId")]
    transform: >-
      return {"$ref": "#/parameters/ConnectionIdParameter"}
typescript:
 add-credentials: true
 generate-metadata: true
 package-version: 0.0.1
 package-name: "AzureConnectors-Dropbox"
 output-folder: "c:\\Connectors-SDK\\DropBox\\TypeScript"
csharp:
 add-credentials: true
 package-name: "AzureConnectors-Dropbox"
 output-folder: "c:\\Connectors-SDK\\DropBox\\CSharp"
```

**Comment by anganti** [comment]
@daviwil This fixed the issue for now. Need to do some more validation.
https://github.com/Azure/autorest/issues/964#issuecomment-302719023

```yaml
input-file: "c:\\Connectors-SDK\\src\\AzureConnectorsSdk.Tests\\SampleFiles\\dropbox-openapi.json"
version: V2
pass-thru: "schema-validator-swagger"
directive:
  - from: swagger-document
    where: $.paths.*.*
    transform: $.operationId = `${( $.tags || [] )[0] || "dropbox" }_${$.operationId}`  
  - from: swagger-document
    where: $
    transform: >-
      $["parameters"] = {"ConnectionIdParameter": { "name": "connectionId", "in": "path", "required": true, "type": "string" }}
  - from: swagger-document
    where: $.paths.*.*.parameters[?(@.name === "connectionId")]
    transform: >-
      return {"$ref": "#/parameters/ConnectionIdParameter"}
typescript:
 add-credentials: true
 generate-metadata: true
 package-version: 0.0.1
 package-name: "AzureConnectors-Dropbox"
 output-folder: "c:\\Connectors-SDK\\DropBox\\TypeScript"
csharp:
 add-credentials: true
 package-name: "AzureConnectors-Dropbox"
 output-folder: "c:\\Connectors-SDK\\DropBox\\CSharp"
  

```
