### ISSUE TITLE
[v6] Error generating from latest schema registry swagger: duplicate object schemas

### ISSUE THREAD

**Issue by nguerrera** [Azure/autorest.typescript#736]
I'm trying to update schema-registry generated code for TypeScript

Given this configuration:
``` yaml
description: Generated Schema Registry Client
generate-metadata: false
add-credentials: false
license-header: MICROSOFT_MIT_NO_VERSION
output-folder: ../
source-code-folder-path: ./src/generated
input-file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/1e23d91e875e4464e57667639e06408cef99868d/specification/schemaregistry/data-plane/Microsoft.EventHub/preview/2020-09-01-preview/schemaregistry.json
use-extension:
  "@autorest/typescript": "6.0.0-dev.20200918.1"
```

I get:
```
ERROR (): Duplicate object schemas with 'SerializationType' name  detected.
FATAL: Error: 1 errors occured -- cannot continue.
  Error: Plugin checker reported failure.
```

I am not sure if this is an issue with the swagger authoring (cc @arerlend)  or with the generator (cc @joheredi).
