### ISSUE TITLE
Can't get into !$(profile) yaml condition when using track2 code generator

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#880]
You can take resources RP as a example to repro this.  The readme.typescript.md of batch part is defined like this:
~~~
```yaml $(typescript) && !$(profile)
typescript:
  azure-arm: true
  batch: true
  generate-metadata: true
batch:
  - package-resources: true
  - package-features: true
  - package-locks: true
  - package-policy: true
  - package-links: true
  - package-managedapplications: true
```
~~~
The command I am running is 
`autorest --typescript ../azure-rest-api-specs/specification/resources/resource-manager/readme.md --output-folder=. --clear-output-folder –debug ` 
            And it says no input files provided.
            
 
But if I remove the !$(profile) in yaml condition like
~~~
```yaml $(typescript)
typescript:
  azure-arm: true
  batch: true
  generate-metadata: true
batch:
  - package-resources: true
  - package-features: true
  - package-locks: true
  - package-policy: true
  - package-links: true
  - package-managedapplications: true
```
~~~

 It can generate the batch task one by one correctly. And any other conditions like ```yaml $(typescript) && !$(aaaa) also works.  I guess there is somewhere defined  profile in track2 generator causing this !$(profile) can never be true?
